Home directory in Docker now fully accessible
DCAN-Labs/BIBSnet pull request #141
Opened 2024-10-07 19:50 UTC by joey-scanga

This changes the permissions of the created home directory at /home/bibsnet to ensure that the container has complete access

2024-10-08 22:35 UTC, scott-huberty commented
xref the recently merged #134 - which IIRC gave all users permission to read/execute but not write. 

@joey-scanga  What version of BIBSnet are you using and I'm curious if you hit an error specifically due to write permissions?

2024-10-12 00:20 UTC, LuciMoore commented
@joey-scanga to echo @scott-huberty, can you confirm which BIBSNet version you are using before we approve this merge? Thank you for your help!!!

2024-10-12 00:24 UTC, LuciMoore requested changes
Can you confirm that you hit this error when using the most recent version 3.4.2? I believe the permissions issues were resolved with the latest release, but if not then we'll merge. thank you for your help!

2024-11-27 05:33 UTC, LuciMoore commented
I'm closing this PR for now, but please re-open it if the latest version still requires this update!

2024-11-27 05:40 UTC, closed without merging